# Generated by Django 2.1.7 on 2019-06-01 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='defaultp.jpg', upload_to='profile_pics'),
        ),
    ]
