# Generated by Django 2.1.7 on 2019-06-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='defaultp.jpg', upload_to='profile_pics'),
        ),
    ]
